#!/bin/sh

# easy config editing
alias nvimrc=$EDITOR' ~/.config/nvim/'
alias zshrc=$EDITOR' ~/.config/zsh/'

# paru aliases
if [ -x "$(command -v paru)" ]; then
    alias p="paru -Sl | fuzpac"
    alias psyu="paru -Syyu"
    alias ps="paru -S"
    alias pss="paru -Sl | fuzpac"
fi

# get fastest mirrors
alias mirror="sudo reflector --ipv4 --protocol https --country Netherlands,Germany,England,France --latest 10 --sort rate --verbose --save /etc/pacman.d/mirrorlist"

# pipe to 'clip' to copy output
alias clip='xclip -selection clipboard'

# Paste clipboard content to selected window
alias pasteto='xclip -selection clipboard -out | tr \\n \\r | xdotool selectwindow windowfocus type --clearmodifiers --delay 25 --window %@ --file -'

# tf2 folder
alias tf2map='cd ~/.local/share/Steam/steamapps/common/Team\ Fortress\ 2/tf'

# remapping core utils to better alternatives
alias vim=$EDITOR
alias v=$EDITOR
[ -x "$(command -v bat)" ] && alias cat='bat'
[ -x "$(command -v eza)" ] && alias ls='eza -alhg --group-directories-first'
alias mkdir='mkdir -pv'
[ -x "$(command -v nala)" ] && alias apt='nala'
[ -x "$(command -v nala)" ] && alias apt-get='nala'

# kitty ssh
[[ $TERM == "xterm-kitty" ]] && alias ssh='kitty +kitten ssh'

alias nv="nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"

alias update="mirror && topgrade && initramfs"

alias fixaudio="systemctl --user restart pipewire.service pipewire-pulse.service"

# maven
alias sbom-docker="mvn exec:exec@generate-sbom-docker exec:exec@scan-sbom-docker --fail-at-end | grep --extended-regexp 'NAME*INSTALLED*FIXED-IN*TYPE*VULNERABILITY*SEVERITY|Critical|High'"
alias mvn-get-updates="mvnd -DprocessDependencyManagement=false -DshowVersionless=false versions:display-parent-updates versions:display-dependency-updates versions:display-property-updates versions:display-plugin-updates | grep --extended-regexp 'display-.*-updates|->'"
# alias mvn-get-updates="mvnd -DprocessDependencyManagement=false versions:display-parent-updates versions:display-dependency-updates versions:display-property-updates versions:display-plugin-updates | grep --extended-regexp 'display-.*-updates|->'"
# alias mvn-get-minor-updates="mvnd -DprocessDependencyManagement=false -DallowMajorUpdates=false versions:display-parent-updates versions:display-dependency-updates versions:display-property-updates versions:display-plugin-updates | grep --extended-regexp 'display-.*-updates|->'"
alias mvn-get-minor-updates="mvnd -DprocessDependencyManagement=false -DallowMajorUpdates=false -DshowVersionless=false versions:display-parent-updates versions:display-dependency-updates versions:display-property-updates versions:display-plugin-updates | grep --extended-regexp 'display-.*-updates|->'"

