#!/bin/sh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/jari/.conda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/jari/.conda/etc/profile.d/conda.sh" ]; then
        . "/home/jari/.conda/etc/profile.d/conda.sh"
    else
        export PATH="/home/jari/.conda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

