#!/bin/sh

# only do this when not in lf (lf uses seperate cleaner)
[[ -v LF_LEVELL ]] || kitty +kitten icat --silent --transfer-mode stream --clear

fileName=$1
width=$2
height=$3
left=$4
top=$5

function fallback () {
    pistol $fileName $width $height $left $top
}

function handleImage () {
    if [[ $TERM == "xterm-kitty" ]]; then
        kitty +kitten icat --transfer-mode stream --place "${width}x${height}@${left}x${top}" --scale-up --stdin=no $1
        exit 1
    else
        fallback
    fi
}

function handlePdf () {
    if [[ $TERM == "xterm-kitty" ]]; then
        CACHE=$(mktemp /tmp/thumbcache.XXXXX)
        pdftoppm -png -f 1 -singlefile "$1" "$CACHE"
        handleImage "$CACHE.png"
    else
        fallback
    fi
}

function handleVideo () {
    if [[ $TERM == "xterm-kitty" ]]; then
        CACHE=$(mktemp /tmp/thumbcache.XXXXX)
        ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
        handleImage "$CACHE"
    else
        fallback
    fi
}

# check for file extensions
case "$fileName" in
	*.tgz|*.tar.gz) tar tzf "$1" ;;
	*.tar.bz2|*.tbz2) tar tjf "$1" ;;
	*.tar.txz|*.txz) xz --list "$1" ;;
	*.tar) tar tf "$1" ;;
	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1";;
	*.rar) unrar l "$1";;
	*.7z) 7z l "$1";;
	*.[1-8]) man "$1" | col -b ;;
	*.o) nm "$1" | less ;;
	*.doc) catdoc "$1" ;;
	*.docx) docx2txt "$1" - ;;
    *.csv) bat $fileName ;;
    *.pdf) handlePdf $fileName ;;
	*.jpg|*.jpeg|*.png) handleImage $fileName ;;
	*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx) handleVideo $fileName ;;
esac

# check mime types
case "$(file -Lb --mime-type -- "$fileName")" in
    text/*) bat $fileName ;;
    image/*) handleImage $fileName ;;
    video/*) handleVideo $fileName ;;
    *) fallback 
esac



