#!/bin/sh

# only do this when not in lf (lf uses seperate cleaner)
[[ -v LF_LEVELL ]] || kitty +kitten icat --silent --transfer-mode stream --clear
# kitty +kitten icat --silent --transfer-mode stream --clear


fileName="$1"
width="$(($2-4))"
height="$(($3-4))"
left="$(($4))"
top="$(($5))"

function fallback () {
    pistol "$1" "$width" "$height" "$left" "$top"
}

function handleImage () {
    if [ $TERM == "xterm-kitty" ]; then
        kitty +kitten icat --silent --transfer-mode stream --place "${width}x${height}@${left}x${top}" --align left "$1"
        exit 1
    elif [ $TERM_PROGRAM == "WezTerm" ]; then
        wezterm imgcat "$1"
    else
        fallback "$1"
    fi
}

function handlePdf () {
    if [ $TERM == "xterm-kitty" ] || [ $TERM_PROGRAM == "WezTerm" ]; then
        CACHE="$(mktemp /tmp/thumbcache.XXXXX)" &&
        pdftoppm -png -f 1 -singlefile "$1" "$CACHE" &&
        handleImage "$CACHE.png"
    else
        fallback "$1"
    fi
}

function handleVideo () {
    if [ $TERM == "xterm-kitty" ] || [ $TERM_PROGRAM == "WezTerm" ]; then
        if [ ! -f "/tmp/thumbcache/$1.jpeg" ]; then
            mkdir -p /tmp/thumbcache/"$PWD"
            ffmpegthumbnailer -i "$1" -o "/tmp/thumbcache/$1.jpeg" -s 0
        fi
        handleImage "/tmp/thumbcache/$1.jpeg"
    else
        fallback "$1"
    fi
}

function handleMimeType () {
    # check mime types
    case "$(file -Lb --mime-type -- "$fileName")" in
        text/*) bat "$fileName";;
        image/*) handleImage "$fileName";;
        video/*) handleVideo "$fileName";;
        *) fallback "$fileName";;
    esac
}

# check for file extensions
case "$fileName" in
    *.txt) bat "$fileName";;
	*.tgz|*.tar.gz) tar tzf "$fileName";;
	*.tar.bz2|*.tbz2) tar tjf "$fileName";;
	*.tar.txz|*.txz) xz --list "$fileName";;
	*.tar) tar tf "$fileName";;
	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$fileName";;
	*.rar) unrar l "$fileName";;
	*.7z) 7z l "$fileName";;
	*.[1-8]) man "$fileName" | col -b;;
	*.o) nm "$fileName" | less;;
	*.doc) catdoc "$fileName";;
	*.docx) docx2txt "$fileName" -;;
    *.csv) bat "$fileName";;
    *.pdf) handlePdf "$fileName";;
	*.jpg|*.jpeg|*.png) handleImage "$fileName";;
	*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx) handleVideo "$fileName";;
    *) handleMimeType;;
esac

