#!/bin/sh

# only do this when not in lf (lf uses seperate cleaner)
[[ -v LF_LEVELL ]] || kitty +kitten icat --silent --transfer-mode stream --clear

fileName="$1"
width="$2"
height="$3"
left="$4"
top="$5"

function fallback () {
    pistol "$1" "$width" "$height" "$left" "$top"
}

function handleImage () {
    if [[ $TERM == "xterm-kitty" ]]; then
        kitty +kitten icat --transfer-mode stream --place "${width}x${height}@${left}x${top}" --scale-up --stdin=no "$1"
        exit 1
    else
        fallback "$1"
    fi
}

function handlePdf () {
    if [[ $TERM == "xterm-kitty" ]]; then
        CACHE="$(mktemp /tmp/thumbcache.XXXXX)"
        pdftoppm -png -f 1 -singlefile "$1" "$CACHE"
        handleImage "$CACHE.png"
    else
        fallback "$1"
    fi
}

function handleVideo () {
    if [[ $TERM == "xterm-kitty" ]]; then
        CACHE="$(mktemp /tmp/thumbcache.XXXXX)"
        ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
        handleImage "$CACHE"
    else
        fallback "$1"
    fi
}

# check for file extensions
case "$fileName" in
    *.txt) bat "$fileName"; return;;
	*.tgz|*.tar.gz) tar tzf "$fileName"; return;;
	*.tar.bz2|*.tbz2) tar tjf "$fileName"; return;;
	*.tar.txz|*.txz) xz --list "$fileName"; return;;
	*.tar) tar tf "$fileName"; return;;
	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$fileName"; return;;
	*.rar) unrar l "$fileName"; return;;
	*.7z) 7z l "$fileName"; return;;
	*.[1-8]) man "$fileName" | col -b; return;;
	*.o) nm "$fileName" | less; return;;
	*.doc) catdoc "$fileName"; return;;
	*.docx) docx2txt "$fileName" -; return;;
    *.csv) bat "$fileName"; return;;
    *.pdf) handlePdf "$fileName"; return;;
	*.jpg|*.jpeg|*.png) handleImage "$fileName"; return;;
	*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx) handleVideo "$fileName"; return;;
esac

# check mime types
case "$(file -Lb --mime-type -- "$fileName")" in
    text/*) bat "$fileName"; return;;
    image/*) handleImage "$fileName"; return;;
    video/*) handleVideo "$fileName"; return;;
    *) fallback "$fileName"; return;;
esac

