#!/bin/bash

set_current_background() {
    #start swwww
    swww query || swww init
    #set the current background
    swww img ~/.config/wallpapers/Arch_kiss.jpg
}


if [[ "$1" == "setbg" ]]; then
    set_current_background
fi

TOOLTIP='Default Keybinds\n'\
'SUPER + Q = Start Kitty\n'\
'SUPER + F4 = Close Window\n'\
'SUPER + L = Lock Screen\n'\
'SUPER + M = Logout menu\n'\
'SUPER + E = File Manager\n'\
'SUPER + V + Toggle Float\n'\
'SUPER + SPACE = App Launcher\n'\
'SUPER + S = Screenshot'

echo '{"text": "'$VER'", "tooltip": "'$TOOLTIP'"}'
